### PR TITLE
Fix compilation with MinGW32 runtime

### PR DESCRIPTION
**Pull request by pali**

### CODE REVIEW

**Comment by pali** [comment]
@jwbargsten: Could you look at this PR?

**Review by jwbargsten — APPROVED** [review]
OK, let's see what happens :)

**Comment by jwbargsten** [comment]
Thanks for contributing (and waiting)

**Comment by jwbargsten** [comment]
Published as v0.636

**Comment by pali** [comment]
Works fine now!
Previously AppVeyor CI showed error message:
```
! Installing Proc::ProcessTable failed. See C:\Users\appveyor\.cpanm\work\1684173654.2200\build.log for details. Retry with --force to force install it.
```
And now it show:
```
Successfully installed Proc-ProcessTable-0.636
```
So issue is really fixed.

**Pull request merged**
